In [ ]:
import numpy as np
a = [1,2,3,4]
b = [5,6,7,8]
a+b


[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
[a[i] + b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [ ]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[2:]

array([[7, 8, 9]])

In [ ]:
arr[1:,1:]   ##start_row:end_row,start_col:end_colum

array([[5, 6],
       [8, 9]])

In [ ]:
arr[:,1:2] #start_row:end_row,start_col:end_column

array([[2],
       [5],
       [8]])

In [ ]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [ ]:
np.eye(3,3).astype(int).dtype

dtype('int64')

In [ ]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[a>2]

array([3, 4])

In [ ]:
np.linspace(0,10,5)   # it will divide it by 5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
### vector operations with scalar values

In [ ]:
a = np.array([1,2,3])
a**2

array([1, 4, 9])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array ([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
np.dot(a,b)    #for multiplication of vectors

array([[19, 22],
       [43, 50]])

In [ ]:
a.T                       #for transpose

array([[1, 3],
       [2, 4]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a_non_singular = np.array([[1,2],[3,4]])
np.linalg.inv(a_non_singular)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.det(a)         # for determenent

np.float64(-2.0000000000000004)

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array ([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [ ]:
np.hstack((a,b))    #for horizantal

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.vstack((a,b))     #for vertical


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,4,1])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,4,1])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [ ]:
np.split(a,2)#for split

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  1])]

In [ ]:
arr = np.array([1,2,3,4,5,6])


In [ ]:
b = arr.view()

In [ ]:
b[0] = 10

In [ ]:
arr , b

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [ ]:
c = arr.copy()     #for copy

In [ ]:
arr, c

(array([10,  2,  3,  4,  5,  6]), array([11,  2,  3,  4,  5,  6]))

In [ ]:
c[0] = 11

In [7]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array ([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [8]:
np.sum(a,axis=0)

array([4, 6])

In [10]:
np.array([12, 15, 18])

array([12, 15, 18])

In [11]:
np.sum(a,axis=1)

array([3, 7])

In [13]:
np.array([6, 15, 24])

array([ 6, 15, 24])

In [14]:
#we have to creat a methods by using numpy

In [15]:
def mean(array):
  n = len(array)
  return np.sum(array)/n


In [16]:
mean(np.array([1,2,3,4,5,6]))

np.float64(3.5)

In [21]:
def variance(array):
  n = len(array)
  m = mean(array)
  return np.sum((array - m)**2)/n

In [22]:
variance(np.array([1,2,3,4,5,6]))

np.float64(2.9166666666666665)

In [37]:
##min-max scalling using numpy

In [23]:
def min_max_scaler(array):
    array = np.array(array)
    min_val = np.min(array)
    max_val = np.max(array)
    scaled = (array - min_val) / (max_val - min_val)
    return scaled


In [24]:
min_max_scaler(np.array([1,2,3,4,5,6]))


array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
##standard  scaler

In [25]:
def standard_scaler(array):
    array = np.array(array)
    mean_val = np.mean(array)
    std_val = np.std(array)
    scaled = (array - mean_val) / std_val
    return scaled


In [26]:
standard_scaler(np.array([1,2,3,4,5,6]))


array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

In [ ]:
#sigmoid function

In [27]:
def sigmoid(array):
    array = np.array(array)
    return 1 / (1 + np.exp(-array))


In [28]:
sigmoid(np.array([0, 1, -1, 2]))


array([0.5       , 0.73105858, 0.26894142, 0.88079708])

In [ ]:
# Relu function

In [29]:
def relu(array):
    array = np.array(array)
    return np.maximum(0, array)


In [30]:
relu(np.array([-2, -1, 0, 3, 5]))


array([0, 0, 0, 3, 5])

In [ ]:
#leaky_relu function

In [31]:
def leaky_relu(array, alpha=0.01):
    array = np.array(array)
    return np.where(array > 0, array, alpha * array)


In [32]:
leaky_relu(np.array([-5, -1, 0, 2, 4]))


array([-0.05, -0.01,  0.  ,  2.  ,  4.  ])

In [ ]:
# softmax function

In [33]:
def softmax(array):
    array = np.array(array)
    exp_vals = np.exp(array - np.max(array))   # for numerical stability
    return exp_vals / np.sum(exp_vals)


In [34]:
softmax(np.array([2, 1, 0]))


array([0.66524096, 0.24472847, 0.09003057])

In [ ]:
# sigmoid deveration

In [35]:
def sigmoid_derivative(array):
    array = np.array(array)
    sig = 1 / (1 + np.exp(-array))   # sigmoid
    return sig * (1 - sig)


In [36]:
sigmoid_derivative(np.array([0, 1, -1]))


array([0.25      , 0.19661193, 0.19661193])